apiVersion: sofe/v1
kind: Policy
metadata:
  name: ebs-gp2-upgrade-to-gp3
  description: EBS volumes still on gp2 (gp3 is 20% cheaper with better performance)
  tags:
  - cost-optimization
  - storage
spec:
  scope:
    resource_types:
    - aws.ebs
  rule:
    metric: volume_type_gp2
    operator: ==
    threshold: 1
  message: 'volume_type_gp2 = {value} (threshold: =={threshold})'
  recommendation: Migrate from gp2 to gp3 for 20% cost savings and better baseline
    IOPS
  severity: low
