apiVersion: sofe/v1
kind: Policy
metadata:
  name: secrets-not-rotated
  description: "Secrets without rotation enabled are a security risk"
  author: carlos@brickstore.ai
  tags: [security, governance, secrets]
spec:
  scope:
    resource_types: [aws.secretsmanager]
    regions: ["*"]
    accounts: ["*"]
  rule:
    metric: rotation_enabled
    operator: "=="
    threshold: 0
  severity: medium
  actions:
    - type: finding
    - type: recommend
      suggestion: "Enable automatic rotation for this secret"
